version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    container_name: "redis"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"


  botapp:
    restart: always
    build: ./botapp
    ports:
      - "443:5000"

    env_file:
      - settings.env

    depends_on:
      - redis
      - mongo
    command: gunicorn app:app --config=gunicorn_settings.py

  senderapp:
    restart: always
    build: ./botapp
    env_file:
      - settings.env

    depends_on:
      - redis
      - mongo
    command: celery -A sender worker -B